# Generated by Django 5.1.7 on 2025-03-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
