# Generated by Django 5.1.7 on 2025-03-16 10:33

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('short_code', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('clicks', models.IntegerField(default=0)),
                ('interstitial1_title', models.CharField(default='Please wait...', max_length=100)),
                ('interstitial1_message', models.TextField(default="Your link is being processed. You'll be redirected shortly.")),
                ('interstitial1_wait_time', models.IntegerField(default=5)),
                ('interstitial1_background', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('interstitial1_text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('interstitial2_title', models.CharField(default='Almost there...', max_length=100)),
                ('interstitial2_message', models.TextField(default='Just one more step before you reach your destination.')),
                ('interstitial2_wait_time', models.IntegerField(default=5)),
                ('interstitial2_background', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('interstitial2_text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_data', to='shortener.url')),
            ],
        ),
    ]
