# Generated by Django 5.1.7 on 2025-03-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_identifier', models.CharField(max_length=255)),
                ('last_earning_date', models.DateField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_trackers', to='shortener.url')),
            ],
            options={
                'unique_together': {('url', 'device_identifier')},
            },
        ),
    ]
