# Generated by Django 5.1.7 on 2025-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_devicetracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetracker',
            name='last_earning_date',
            field=models.DateField(auto_now=True),
        ),
    ]
